name: "simple workflow pm2"
#event, trigger every we push code to repository
on: [push]
jobs:
  check-pm2-version:
    #runner, job dijalankan di server ubuntu terbaru
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #checkout code dari repository agar bisa dijalankan di runner.
      - uses: actions/setup-node@v3
      - run: npm install pm2@latest -g
      - run: pm2 -V
      - run: pm2 list
      - run: pm2 start index.js -i max
      - run: pm2 list
